
on:
  push:
    branches:
      - master
      - main

name: book-workflow

jobs:
  bookdown:
    name: Render Book
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ hashFiles('DESCRIPTION') }}

      - name: Install dependencies
        run: Rscript -e 'install.packages("remotes")' -e 'options(install.packages.check.source = "both")' -e 'remotes::install_deps(dependencies = TRUE)'

      - name: Render book html
        run: Rscript -e 'bookdown::render_book("index.Rmd")'
        env: # Set the secret as an input
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}

      - uses: actions/setup-node@v1

      - name: Install paged-js
        run: npm install . -g

      - name: PDF
        run: Rscript -e 'pagedjs-cli ./_book/index.html -o result.pdf'
